package application;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class MainSceneController {

	// Event Listener on Button.onAction
	@FXML
	private TextField TextField_ID;
	
	public void BtnAuthentification(ActionEvent event) {
		// TODO Autogenerated
		
		
	}
	// Event Listener on PasswordField.onAction
	@FXML
	public void TextField_mdp(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField.onAction
	@FXML
	public void TextField_ID(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink.onAction
	@FXML
	public void LinkReinitialisation(ActionEvent event) {
		// TODO Autogenerated
	}
}
